---
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      secrets:
        - admin_password
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./data/files:/data/files:ro
      - ./data/secrets/certbot:/var/www/certbot
      - ./data/secrets/letsencrypt:/etc/letsencrypt
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
  
  certbot:
    image: certbot/certbot
    profiles:
      - certbot
    volumes:
      - ./data/secrets/certbot:/var/www/certbot
      - ./data/secrets/letsencrypt:/etc/letsencrypt


  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - ./data/files:/data/files
      - ./data/sql:/data/sql
    ports:
      - "127.0.0.1:8000:8000"
secrets:
  admin_password:
    file: ./admin_password.txt
